### ISSUE TITLE
[REQ] Add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [irdkwmnsb/icpc-panasonic-to-visca#1]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [VIDEO section](https://github.com/FORARTfe/HyMPS#-1 ) \ [PTZ page](https://github.com/FORARTfe/HyMPS#pan-tilt-zoom ) \ [Misc](https://github.com/FORARTfe/HyMPS/blob/main/Video/PTZ.md#misc-)), can you please add a GH-compliant license file for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/irdkwmnsb/icpc-panasonic-to-visca)
(badge-generator URL: https://badgen.net/github/license/irdkwmnsb/icpc-panasonic-to-visca)

You can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by irdkwmnsb** [comment]
Hello! Thank you!  
That's quite unexpected for me :D   
Added the MIT License as it's the one I prefer for my open source projects  
https://github.com/irdkwmnsb/icpc-panasonic-to-visca/commit/f23b6f19a7b1ce2618a5bf9e6ef36272f415b982
